# Personal info
name: Nicholas Alvino
title: Computer Science
email: naalvino@optonline.net

# Social links
github_username:  naalvino
linkedin_username: nicholasalvino


# About Section
about_profile_image: profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a college sophomore eager to enter the working world in the field of technology, specifically
  Cybersecurity. I am keen to develop new skills to complement my studies as a Computer Science,
  Cybersecurity major and to progress in the technology field. Computers are my passion, allowing me to
  enjoy learning new concepts and topics such as encryption methods. My goal is to acquire a professional
  position in cybersecurity or computer science where I can utilize my relevant experience, technical
  expertise, and problem-solving skills.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
#more_content: | # this will include new lines to allow paragraphs
#  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#   - Rock climbing
#   - Gaming
#   - Knitting
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
